FROM python:3.10-slim-bookworm

WORKDIR /opt/grader

RUN apt-get update && \
    apt-get install -y --no-install-recommends ffmpeg gcc git libglib2.0-0 libgomp1 libpq-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.grader.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.grader.txt

COPY app/ app/

ENV PYTHONUNBUFFERED=1

CMD ["python3", "-m", "app.worker"]
